default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: discourse_hub_development
test:
  <<: *default
  database: discourse_hub_test
production:
  <<: *default
  database: discourse_hub_production
