FROM nginx

RUN apt-get update -qq && apt-get -y install apache2-utils

ENV RAILS_ROOT /var/www/discoursehub

WORKDIR $RAILS_ROOT

RUN mkdir log

COPY public public/

COPY config/containers/nginx/default.conf  /etc/nginx/conf.d/default.conf

CMD [ "nginx", "-g", "daemon off;" ]
